# Generated by Django 5.1.3 on 2024-11-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='account',
            field=models.ManyToManyField(to='users.account'),
        ),
    ]
