# Generated by Django 5.1.3 on 2024-11-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_productgroup_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.transaction'),
        ),
    ]
