# Generated by Django 5.1.3 on 2024-11-23 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_transactionitem_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='account',
            new_name='accounts',
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.product'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='users.transaction'),
            preserve_default=False,
        ),
    ]
