"""
Django settings for API project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lobp1t87(a-#7nuh34c366egx_t%k%7b51#hivva)_pxj!0chc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

ROOT_URLCONF = 'API.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'API.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# Let's stick to sqlite for now. We'll migrate to postgres once docker is ready.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# TODO: remove the default key, as it may lead to security issues, also, maybe move this to a separate file, looks awful tbh
JWT_PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAkbet5pk3AAXAkZQSuBlJHfG3corRFTagfWk7x6lVwHD0WPv7QWJuLEQJUF5wHuKi2Fr070XAOTtzD2cHcyaOnrjCLchKlfnz1eJlgnSsW0kKmQF+JNdxw3I5Ys3FdSZvbI51IR5fsmdUyiveSSvirIonwVCQQ9qp9oqCcd46kT9+gy6vy38aXmhOBBULS2+oqvUDf5td+hNvLndQQoquOLvXb/akt5+dYORvAiLCMXMZWxo/yK5dxnNe+GvjgAWNjtj9xqmJs4WFj9TJR8HrJpWeEJdM408V5ULKxflofNl/VflDpbdmF9SbOgJ1uSYO75yBAKjkTeiwXy+BUHhafQIDAQABAoIBAGaYm+FTmQzz/9zAE9n5O6jQqqgEIyg7eQ4zzLpMeKrxHKmWaRZlNksGcERc6bZlPeD1UaUySCBDwkRi9zTVPe91CIrxjcpA3bSHHY+XlE8Fg2etTGKmKlxBDTSKyu8r66HUP5Xc6+YRqPpbnruIIaX38/vBPIH58Fc8uJFxtWzT5hDkjz6FWNZyHjZilONGAXGlJk5/i1QvEUaBgms694tTGAgJFMqh8Ga6Q+u3G5IkRSpD+4iaKdffl8g+FYjUkVE+UfKc+SUU8+XtC4I777jp76huGeO0q43rzOPozwV08BnjfeAGZaFOssKvzQmhOVwuJ79bvhsZmTumT954VOECgYEAz5oFA8Yz/r+56yFoOwOS+p1ZnoIGPBL0Gu5LmeC6e/e18dzkIqzK6Rejoe9rF2VzgaqacCo4Nuf5LVems+apsFpLZlYMms2HZbDj0pKgpS6zXe0DPtxCzYIAce4kckBRxLiKWWuZFGeuPR6WuDXWewN0/9W1uKVIfODqFowVDvUCgYEAs7BSAq9hOcTHg9IqWf+wZzJIBoFJYaOwrYaCVVPMBRpd5Y6gtBNTiUTfQMgdHaNy/RY0LqQxu1aMtCwz3RcR2nRcwHCUhhjRLMmGwxUGMDiY4vVyw+QdZwDyeVVoBEm5NrlaWCmpYYHKCbQl18qRSb0CpljwmWjWPI08j0NNWGkCgYBrXBdj0EhrYfNf6bLhcgO8n0sNceiPgK3Ej5+BQHqwSXZKUhWY6Qs2aAczY4FaZBjL4dJkVzEjE+wEyuNm/c6baNa9YZq7I7b1m/j1mOaDBhe0ZzHafEX/yU85nBI1E5Y1ycmiXMaZitTMvtjrAsycaTlEZNzJVJCcJCRq7J6nUQKBgQCaJW8lKIiSgzHY7skwLb2JucO5+N0XqtHc+qACTQGfexAD5sgL0ux9vJx8uW7oxxfU72BShr63BDduNOFFEA5bxijvWWTAaLfA4Rz/a6DEazkUshUC4UUr4M8hsVerHgeKX5WWPh81K59DlcxFA1yB0mhchb3ZDOuERHEoQUcvyQKBgQDL2yDfkFggSF8GClGgJ1wLMWCLukXMaVm0RP3he3bjZoi4oFEAc2Ekpqye8e+mV/flVkaNg6hvB2VyNjdqNy9Uxs5A6n4tE2wxH4HyRXFpL4qKmNG5da39dPkkFs0jGy8cwnX3gwPpy5X7TqXag72n9lyrWIIexoNSpia6go23Jg==\n-----END RSA PRIVATE KEY-----"
JWT_PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkbet5pk3AAXAkZQSuBlJHfG3corRFTagfWk7x6lVwHD0WPv7QWJuLEQJUF5wHuKi2Fr070XAOTtzD2cHcyaOnrjCLchKlfnz1eJlgnSsW0kKmQF+JNdxw3I5Ys3FdSZvbI51IR5fsmdUyiveSSvirIonwVCQQ9qp9oqCcd46kT9+gy6vy38aXmhOBBULS2+oqvUDf5td+hNvLndQQoquOLvXb/akt5+dYORvAiLCMXMZWxo/yK5dxnNe+GvjgAWNjtj9xqmJs4WFj9TJR8HrJpWeEJdM408V5ULKxflofNl/VflDpbdmF9SbOgJ1uSYO75yBAKjkTeiwXy+BUHhafQIDAQAB\n-----END PUBLIC KEY-----"
SIMPLE_JWT = {
    "ALGORITHM" : "RS512", 
    "SIGNING_KEY" : os.getenv('JWT_SECRET', JWT_PRIVATE_KEY), 
    "VERIFYING_KEY" : os.getenv('JWT_PUBLIC', JWT_PUBLIC_KEY)
}