// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: morpheus.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictProductNamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receipt string `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Token   string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *PredictProductNamesRequest) Reset() {
	*x = PredictProductNamesRequest{}
	mi := &file_morpheus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictProductNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictProductNamesRequest) ProtoMessage() {}

func (x *PredictProductNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_morpheus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictProductNamesRequest.ProtoReflect.Descriptor instead.
func (*PredictProductNamesRequest) Descriptor() ([]byte, []int) {
	return file_morpheus_proto_rawDescGZIP(), []int{0}
}

func (x *PredictProductNamesRequest) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

func (x *PredictProductNamesRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type PredictedProductNames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredictedName []string `protobuf:"bytes,1,rep,name=predictedName,proto3" json:"predictedName,omitempty"`
}

func (x *PredictedProductNames) Reset() {
	*x = PredictedProductNames{}
	mi := &file_morpheus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictedProductNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedProductNames) ProtoMessage() {}

func (x *PredictedProductNames) ProtoReflect() protoreflect.Message {
	mi := &file_morpheus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedProductNames.ProtoReflect.Descriptor instead.
func (*PredictedProductNames) Descriptor() ([]byte, []int) {
	return file_morpheus_proto_rawDescGZIP(), []int{1}
}

func (x *PredictedProductNames) GetPredictedName() []string {
	if x != nil {
		return x.PredictedName
	}
	return nil
}

type PredictProductNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredictedProductNamesList []*PredictedProductNames `protobuf:"bytes,1,rep,name=predictedProductNamesList,proto3" json:"predictedProductNamesList,omitempty"`
}

func (x *PredictProductNamesResponse) Reset() {
	*x = PredictProductNamesResponse{}
	mi := &file_morpheus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictProductNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictProductNamesResponse) ProtoMessage() {}

func (x *PredictProductNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_morpheus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictProductNamesResponse.ProtoReflect.Descriptor instead.
func (*PredictProductNamesResponse) Descriptor() ([]byte, []int) {
	return file_morpheus_proto_rawDescGZIP(), []int{2}
}

func (x *PredictProductNamesResponse) GetPredictedProductNamesList() []*PredictedProductNames {
	if x != nil {
		return x.PredictedProductNamesList
	}
	return nil
}

var File_morpheus_proto protoreflect.FileDescriptor

var file_morpheus_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x6f, 0x72, 0x70, 0x68, 0x65, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x6f, 0x72, 0x70, 0x68, 0x65, 0x75, 0x73, 0x22, 0x4c, 0x0a, 0x1a, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3d, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7c, 0x0a, 0x1b, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x19, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x6f, 0x72, 0x70,
	0x68, 0x65, 0x75, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x19, 0x70, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x70, 0x0a, 0x08, 0x4d, 0x6f, 0x72, 0x70, 0x68, 0x65, 0x75,
	0x73, 0x12, 0x64, 0x0a, 0x13, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x24, 0x2e, 0x6d, 0x6f, 0x72, 0x70, 0x68,
	0x65, 0x75, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x6d, 0x6f, 0x72, 0x70, 0x68, 0x65, 0x75, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x73, 0x72, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_morpheus_proto_rawDescOnce sync.Once
	file_morpheus_proto_rawDescData = file_morpheus_proto_rawDesc
)

func file_morpheus_proto_rawDescGZIP() []byte {
	file_morpheus_proto_rawDescOnce.Do(func() {
		file_morpheus_proto_rawDescData = protoimpl.X.CompressGZIP(file_morpheus_proto_rawDescData)
	})
	return file_morpheus_proto_rawDescData
}

var file_morpheus_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_morpheus_proto_goTypes = []any{
	(*PredictProductNamesRequest)(nil),  // 0: morpheus.PredictProductNamesRequest
	(*PredictedProductNames)(nil),       // 1: morpheus.PredictedProductNames
	(*PredictProductNamesResponse)(nil), // 2: morpheus.PredictProductNamesResponse
}
var file_morpheus_proto_depIdxs = []int32{
	1, // 0: morpheus.PredictProductNamesResponse.predictedProductNamesList:type_name -> morpheus.PredictedProductNames
	0, // 1: morpheus.Morpheus.PredictProductNames:input_type -> morpheus.PredictProductNamesRequest
	2, // 2: morpheus.Morpheus.PredictProductNames:output_type -> morpheus.PredictProductNamesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_morpheus_proto_init() }
func file_morpheus_proto_init() {
	if File_morpheus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_morpheus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_morpheus_proto_goTypes,
		DependencyIndexes: file_morpheus_proto_depIdxs,
		MessageInfos:      file_morpheus_proto_msgTypes,
	}.Build()
	File_morpheus_proto = out.File
	file_morpheus_proto_rawDesc = nil
	file_morpheus_proto_goTypes = nil
	file_morpheus_proto_depIdxs = nil
}
