name: Go CI

on:
  push:
    paths:
      - 'morpheus/**'
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
    linting: 
        name: Linting
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v1
          with:
            version: v1.28
            working-directory: ./morpheus
