name: Go CI

on:
  push:
    paths:
      - 'morpheus/**'
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  ci: 
    name: Go - CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./morpheus

    steps:
    - name: Fetch repo
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'

    - name: pull dependencies
      run: go mod tidy

    - name: linting
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.62.0
        ./bin/golangci-lint run

    - name: run tests
      run: go test ./...
