name: Go CI

on:
  push:
    paths:
      - 'morpheus/**'
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
    linting: 
        name: Linting
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Golangci-lint
          uses: golangci/golangci-lint-action@v6.1.1
        
        - name: enter morpheus
          run: cd morpheus
        - name: lint
          run: golangci-lint run
