name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
    linting: 
        name: Linting
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: set up Python 3.12
          uses: actions/setup-python@v2
          with:
            python-version: 3.12

        - name: install dependencies
          run: pip install -r requirements.txt
        
        - name: code linting
          run: ruff check
