name: Python CI

on:
  push:
    branches:
      - '**'

jobs:
    linting: 
        name: Linting
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: set up Python 3.12
          uses: actions/setup-python@v2
          with:
            python-version: 3.12

        - name: install dependencies
          run: pip install -r API/requirements.txt

        - name: code linting
          run: ruff check

        - name: type checking
          run: python3 -m mypy .

    tests: 
        name: Tests
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: set up Python 3.12
          uses: actions/setup-python@v2
          with:
            python-version: 3.12
        - name: install dependencies
          run: pip install -r API/requirements.txt
        - name: test
          run: python3 -m pytest